[general]
MAIN_FOLDER_ID = "1cbr28a9N7YcW-r0Lv5i99YJEh1KAYFbr"
TEMPLATE_FOLDER_ID = "1updw1-nmohNeQUuM4ZzS7nm3x1JVut_2"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/145oVIxTM4SOr299cdMyheSqZfWMbgBTBO1iLkBqX3Ek/edit?gid=0#gid=0"
type = "service_account"
project_id = "graphico-app-2026"
private_key_id = "9842b1af3bd1f4d74a2e5cc9ee7810deff1dfc64"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDfK+Q7t1nBQ60S
2wmTByKHol4MSueuc8lvLWzQIam9Qw4IgT7Li3TQWxWz72MbI5G+jHyXkw6ijJYj
TAXnlmpupS5McGd5hzlEl9frWmzMuPfnXxQ3ZotaKjt2dHZ7uz+uDoLqGjfdFWJ9
RPrKnVyXkwxAEM6+jXV11tYEFHCjPKVuffm6mHwHSYw+gAYWmigRW1+BDgeuvOHb
2H3QiasJJDjx48LiPW84XIZBL3SBvPfDxJ9x+6hLCvsb8B92ZT8suw4j3BNVavPy
HPzEVocm8OMZ7RXiaq8/u2D9iFoJCGeA6+xLpiqRDrVLXE2esQu4WkXJX5Wb4jbI
CbUZDlphAgMBAAECggEABfcEBv3pPeYo1mvY/1SzJ+bqFpqwmJQVr+K0mYIyKZHa
P9Xx2g+PKWaAglUFVBteRjaLufgUmGROOwFJgx1ybiSnbnmZT8E9LEfWsz6xJm5R
30hGSmNzmWRZlIVGXsZBdyMs0pmtdpD0wfO5tE1XxTaz9B5pjY71sxbxP3NVvgx7
IE1efEH98iv5aJBhJl5EkD0i+EDRzxHTbag0pybAf4LNfBnSKtNFfz/eBWGrCQJd
YUMiuSqRubOlfrpDElAekK9HAYWb4CNOll9Z0DkVbkUA3TuUFXQWfPqKsLYGs7t1
5H7ogmBZE2K2QPvXfDgO4DbWSH8vvoGWksaSORxUhQKBgQD7Z1/ilPs12yOJsGe/
ExusCDJPUWBFjHX/NxN5AQ3TevYzN5txCWPA5ZxCohYo+OkN6rWUnan3OjBvJtge
D+/VQ0IJ9tr21AO5NaUM/6dEesM5FMlgylvV/vSPlbkKY8rbaD8X/rV26cXf8993
nqqat7fU+XNXM9EGhq/xaaLl8wKBgQDjQGIg2N3K2X1rEY9tuwqyntu4ot984GsO
kCrvX0gPWE4gY58j6Uz9/pDr/qBrcQt9XT77AF0n1+ZOnl3xC5OJp4jxWivTUrUF
AEod6ltTVJK6serb3epSDspGxd9HNEtKiB3ZOloOWhn5GD2uSb/vq/XRUUqSDBen
8d/g3RUvWwKBgEk5/grQXC9+qeZEFKPqG+hK5uSFjmYTmJcC4tAfB3ju2uFmNAeD
taOM/avG7G94uOFN2R/1oHkbYNovVUnEWJYkpgqi9XppnMAIqQ+VM5JVs6FftZxU
tNUrEu7zrFcjZAXuYlpJ3W9KflFSBmggNg8krg4Brp/avuqItpy5qTITAoGAKi64
SEqZGN84JZiz2/V9LdzJAkPRYjeyB5kBLz+re5WzotV7I8pZjUgklHnGQ0tPi6y0
VRkjMZMk3/ELlQPGFiYwCETpn6dZjJ0aJOVsoFIxjlAaPUe7CBJQv8RZBrmRRDtx
9vGa59EXwyIZyPFNnGp6DameQu/VsEn4eZ/wH8MCgYAJt7chfWZqdmbMTfBhv6uh
UnXJO/xNBs6VjkdAhXOCZePEoQetSTp2Bwc91Mk30sA568+MuBMyKPkMQmArjKE7
r/A7Mexrh6C2vrAA6ctKfd0tOYNfMBPWMX08qP8IaUN4PqQ2Xz063gZ4CIRhvjCi
41rjlUoMDKDnUYYzWHbFaw==
-----END PRIVATE KEY-----"""
client_email = "graphico-service@graphico-app-2026.iam.gserviceaccount.com"
client_id = "108783194475809831753"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/graphico-service%40graphico-app-2026.iam.gserviceaccount.com"